apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: fitflow

type: Opaque

stringData:
  JWT_SECRET: REPLACE_WITH_JWT_SECRET
  JWT_EXPIRES_IN: 7d
  DATABASE_URL: REPLACE_WITH_DATABASE_URL
