apiVersion: v1
kind: PersistentVolume

metadata:
  name: postgres-pv

spec:
  capacity:
    storage: 5Gi
    
  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual
  
  hostPath:
    # EC2 + Minikube persistent storage path
    path: /mnt/data/postgres

    # Local Mac Minikube testing previously used:
    # path: /data/postgres
    type: DirectoryOrCreate
